true_class(example_0).
true_class(example_1).
true_class(example_2).
true_class(example_3).
true_class(example_4).
true_class(example_5).
true_class(example_6).
true_class(example_7).
true_class(example_8).
true_class(example_9).
true_class(example_10).
true_class(example_11).
true_class(example_12).
true_class(example_13).
true_class(example_14).
true_class(example_15).
